

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "admin1",
    "password": "1234"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}